name = "aiken-extra/tx_util"
version = "1.210.202409"
license = "Apache-2.0"
description = "A Aiken utility library to help constructing ScriptContext"

[repository]
user = "aiken-extra"
project = "tx_util"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"
